### PR TITLE
chore: add details to the readme

### PR DESCRIPTION
**Pull request by csholmq**
Clarify the steps required in order to set this up.

### CODE REVIEW

**Comment by Souvikns** [comment]
**@csholmq firstly thanks for the contribution 🙏🏻**
Let me know when you are done, I will merge this.

**Comment by csholmq** [comment]
I just had one more small commit. But my git credentials didn't work so I need to fix this tonight.

**Comment by csholmq** [comment]
Ready for merge @Souvikns

**Review by Souvikns — APPROVED** [review]
🚀📦

**Pull request merged**
